services:
    api.v2:
        class: Api\V2Bundle\Service\ApiService
        calls:
            - [setContainer, [@service_container]]

    api.v2.order:
            class: Api\V2Bundle\Service\OrderService
            calls:
               - [setContainer, [@service_container]]

    api.v2.place:
            class: Api\V2Bundle\Service\PlaceService
            calls:
                - [setContainer, [@service_container]]

    api.v2.loyalty_card:
            class: Api\V2Bundle\Service\LoyaltyCardService
            calls:
                - [setContainer, [@service_container]]