<?php

namespace Food\ReportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventMailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventMailRepository extends EntityRepository
{

}
