parameters:
#    food_support.example.class: Food\SupportBundle\Example

services:
#    food_support.example:
#        class: %food_support.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
