<?php

namespace Food\ReportBundle\Controller;

use Food\ReportBundle\Entity\OrdersByRestaurantFile;
use Sonata\AdminBundle\Controller\CRUDController as Controller;

class OrdersByRestaurantAdminController extends Controller
{
    public function createAction()
    {
        return parent::createAction(); // TODO: Change the autogenerated stub
    }

    public function listAction()
    {
        $request = $this->admin->getRequest();
        if ($request->isMethod('POST')) {
            $dateFrom = $request->get('dateFrom');
            $dateTo = $request->get('dateTo');
            $types = $request->get('types');
            $restaurants = $request->get('restaurants');
            $this->get('food.report.orders_by_restaurant_service')
                ->generateDocument($types, $restaurants, $dateFrom, $dateTo);
            $request->getSession()->getFlashBag()->add("success", $this->admin->trans('admin.report.documents_generated_preview_in_history'));
            return $this->redirect($request->getUri());
        }
        // List TAB
        $datagrid = $this->admin->getDatagrid();
        $formView = $datagrid->getForm()->createView();
        $this->get('twig')->getExtension('form')->renderer->setTheme($formView, $this->admin->getFilterTheme());

        return $this->render('FoodReportBundle:Report/OrdersByRestaurant:list.html.twig', array(
            'action'     => 'list',
            'form'       => $formView,
            'datagrid'   => $datagrid,
            'csrf_token' => $this->getCsrfToken('sonata.batch'),
            'places'     => $this->get('doctrine.orm.entity_manager')
                ->getRepository('FoodDishesBundle:Place')->findBy(['active' => 1], ['name' => 'ASC']),
            'types'     => OrdersByRestaurantFile::getOrdersByRestaurantFileTypes(),
        ));
    }
}
