parameters:
    locale: lt
    locales: [lt, en, ru]

    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: skanu_lt
    database_user: skanu_lt
    database_password: Z7Uz7VqCWwJP4C2mDJscAFH
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: f6180a0fb30e99a1da1e364412f96c3f98cbaa1f
