services:
    food.cart:
        class: Food\CartBundle\Service\CartService
        arguments: [@service_container]

    food.upload:
        class: Food\AppBundle\Service\UploadService
        arguments: [@service_container, user_id]