<?php

namespace Food\TcgBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TcgLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TcgLogRepository extends EntityRepository
{
}
