<?php

namespace Food\TcgBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Food\OrderBundle\Entity\Order;

/**
 * TcgLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TcgLogRepository extends EntityRepository
{
    public function getByIdSorted(Order $order, $sort)
    {

        $qb = $this->createQueryBuilder('o');
        $qb->setMaxResults( 1 );
        $qb->where('o.order = :order')
            ->andWhere('o.sent =:sent')
            ->setParameters(array(
                'order' => $order,
                'sent' => 1
            ))
            ->orderBy('o.submittedAt', $sort)
        ;

        return $qb->getQuery()
            ->getResult();
    }


}
