parameters:
#    food_api.example.class: Food\ApiBundle\Example

services:
    food_api.api:
        class: Food\ApiBundle\Service\ApiService
        calls:
            - [setContainer, [@service_container]]
