parameters:
#    food_api.example.class: Food\ApiBundle\Example

services:
#    food_api.example:
#        class: %food_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
