<?php

namespace Food\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DuplicatedRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DuplicatedRestaurantRepository extends EntityRepository
{
}
