<?php

namespace Food\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneCodesRepository extends EntityRepository
{
    public function getAllCodes(){

        return $this->findAll();
    }

    public function getActive(){
        return $this->findBy(['active'=>true],['code'=>'DESC']);
    }
}
