<?php

namespace Food\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SlugRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlugRepository extends EntityRepository
{
    public function getByIdAndType($id, $type)
    {
        $slug = $this->findOneBy(array('item_id' => (int) $id, 'type' => $type, 'is_active' => 1));

        if (empty($slug)) {
            return array();
        }

        return $slug;
    }
}
