parameters:
#    call_center.example.class: Food\CallCenterBundle\Example

services:
#    call_center.example:
#        class: %call_center.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
