#food_sms_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: FoodSmsBundle:Default:index }
message_send:
    path:     /messaging-send/{messageId}
    defaults: { _controller: FoodSmsBundle:Send:send }