message_send:
    path:     /messaging-send/{messageId}
    defaults: { _controller: FoodSmsBundle:Send:send }
    methods:  [GET]

delivery_report:
    path:     /messaging-delivery/{provider}
    defaults: { _controller: FoodSmsBundle:Delivery:index, provider: ~ }