<?php

namespace Food\DishesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BannerLinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerLinksRepository extends EntityRepository
{
    public function getBannerLinkByPlace($placeId){
        return $this->findBy(['placeFrom'=>$placeId,'active'=>1]);
    }
}
