services:
    sonata.admin.push:
        class: Food\PushBundle\Admin\PushesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.pushes" }
        arguments:
            - ~
            - Food\PushBundle\Entity\Push
            - ~
        calls:
            - [ setTranslationDomain, [SonataAdminBundle]]