<?php

namespace Food\SupportBundle\Controller;

use Sonata\AdminBundle\Controller\CRUDController as Controller;

class SupportAdminController extends Controller
{
    /**
     * @inheritdoc
     *
     * @codeCoverageIgnore
     */
    public function listAction()
    {
        die();
//        $this->container->get('logger')->alert('OMG!!!!');
//        return parent::listAction(); // TODO: Change the autogenerated stub
    }

}