<?php
// src/AppBundle/Form/Type/CityType.php
namespace Food\AppBundle\Form\Type;

use Sonata\CoreBundle\Tests\Form\Type\Choice;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class GrouppedCheckboxType extends AbstractType
{
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {

        $resolver->setDefaults(array(
        ));

        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub

    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults(array(

        ));
    }



    public function getParent()
    {
        return 'choice';
    }

    public function getName()
    {
        return 'groupped_checkbox';
    }


}