parameters:
#    api_base.example.class: Api\BaseBundle\Example

services:
#    api_base.example:
#        class: %api_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
