food_places_lv_main:
    pattern: /
    defaults: { _controller: FoodPlacesBundle:Default:index}

food_places_lv_recommended:
    pattern: /ieteicama/
    defaults: { _controller: FoodPlacesBundle:Default:index, recommended: 1}

food_places_lv_zaval:
    pattern: /atrs/
    defaults: { _controller: FoodPlacesBundle:Default:index, zaval: 1}

food_change_location:
    pattern: /maina
    defaults: { _controller: FoodPlacesBundle:Default:changeLocation }

food_places_lv_city:
    pattern:  /{city}/
    defaults: { _controller: FoodPlacesBundle:Default:indexCity, city: ~}
    requirements:
        city : "^(?!ieteicama|maina).+"

food_places_lt_city_filter:
    pattern:  /{city}/{slug_filter}
    defaults: { _controller: FoodPlacesBundle:Default:indexCity, city: ~, slug_filter: ~}
    requirements:
        city : "^(?!ieteicama|maina).+"