food_places_lv_main:
    pattern: /
    defaults: { _controller: FoodPlacesBundle:Default:index}

food_places_lv_recommended:
    pattern: /ieteicama/
    defaults: { _controller: FoodPlacesBundle:Default:index, recommended: 1}

food_change_location:
    pattern: /maina
    defaults: { _controller: FoodPlacesBundle:Default:changeLocation }

food_places_lv_city:
    pattern:  /{city}/
    defaults: { _controller: FoodPlacesBundle:Default:indexCity, city: ~}
    requirements:
        city : "^(?!ieteicama|maina).+"