food_places_en_main:
    pattern: /
    defaults: { _controller: FoodPlacesBundle:Default:index}

food_places_en_recommended:
    pattern: /recommended/
    defaults: { _controller: FoodPlacesBundle:Default:index, recommended: 1}