services:
    pirminis_banklink_gateway:
        class: Pirminis\GatewayBundle\Services\BanklinkGateway
        arguments: [@event_dispatcher, "%pirminis_gateway%"]

    pirminis_credit_card_gateway:
        class: Pirminis\GatewayBundle\Services\CreditCardGateway
        arguments: [@event_dispatcher, "%pirminis_gateway%"]
