services:
  sonata.admin.report.orders_by_restaurant:
    class: Food\ReportBundle\Admin\OrdersByRestaurantAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Content", label: "admin.report.orders_by_restaurant" }
    arguments:
      - ~
      - Food\ReportBundle\Entity\OrdersByRestaurantFile
      - 'FoodReportBundle:OrdersByRestaurantAdmin'
    calls:
      - [ setTranslationDomain, [SonataAdminBundle]]

  sonata.admin.report:
      class: Food\ReportBundle\Admin\ReportAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Content", label: "report.all" }
      arguments:
          - ~
          - ~
          - 'FoodReportBundle:Admin\Report'
      calls:
          - [ setTranslationDomain, [SonataAdminBundle]]

  sonata.admin.unique_users_with_placepoints:
      class: Food\ReportBundle\Admin\UniqueUsersWithPlacepointAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Content", label: "report.unique_users_with_placepoints" }
      arguments:
          - ~
          - ~
          - 'FoodReportBundle:Admin\UniqueUsersWithPlacepoint'
      calls:
          - [ setTranslationDomain, [SonataAdminBundle]]

  sonata.admin.valentines:
      class: Food\ReportBundle\Admin\ReportValentinesAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: "Content", label: "valentines.mail" }
      arguments:
          - ~
          - Food\ReportBundle\Entity\EventMail
          - ~
      calls:
          - [ setTranslationDomain, [SonataAdminBundle]]